title: Rail Sakhaviev - CV
description: Rail Sakhaviev - Senior Software Engineer.
url: https://sahaviev.github.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
